AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  StageName:
    Type: String
    Default: prod
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get
            RestApiId: !Ref HelloWorldApi
  HelloWorldFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler2
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get
            RestApiId: !Ref HelloWorldApi
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Variables:
        sv0: "sv0"
        sv1: "sv1"
        stage: !Ref StageName
        version: 1
      CanarySetting:
        PercentTraffic: 30
        StageVariableOverrides:
          sv1: "sv1_new"
          sv2: "sv2_new"
          alias: !Ref StageName
        UseStageCache: false
      DefinitionBody:
        swagger: 2.0
        schemes:
          - https
        info:
          title: APIG-Canary-API
        produces:
          - application/json
        paths:
          "/hello-world":
            get:
              responses:
                "200":
                  description: OK
                  schema:
                    type: string
                    example: Hello World
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub:
                    - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations
                    - { FunctionArn: !GetAtt HelloWorldFunction.Arn }
                    # - { FunctionArn: !GetAtt HelloWorldFunction2.Arn }
